### ISSUE TITLE
Glific header

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#1]
Glific header Design
![image](https://user-images.githubusercontent.com/30264862/93566749-22fdbe80-f9ab-11ea-9c39-a24c116b3e61.png)

**Comment by bohraji** [comment]
@mohitgusain the webinar announcement section is missing.
<img width="1289" alt="Screenshot 2020-09-22 at 12 41 35 PM" src="https://user-images.githubusercontent.com/12884297/93853189-06c29000-fcd1-11ea-822a-13baead35504.png">

**Comment by bohraji** [comment]
@mohitgusain additional feedback - 
The shadow below the navbar is missing.
<img width="1316" alt="Screenshot 2020-09-23 at 12 45 19 PM" src="https://user-images.githubusercontent.com/12884297/93979252-ba438700-fd9a-11ea-8d67-3191c6d23f92.png">
