### ISSUE TITLE
Homepage : Key Features Section

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#10]
Design 
![image](https://user-images.githubusercontent.com/30264862/93686490-43756800-fad4-11ea-918f-ce137f12dffc.png)

**Comment by bohraji** [comment]
@mohitgusain shadow at the end of the section is missing.

<img width="1396" alt="Screenshot 2020-09-22 at 12 49 05 PM" src="https://user-images.githubusercontent.com/12884297/93853761-17273a80-fcd2-11ea-9874-af65538f52e0.png">
