### ISSUE TITLE
Get Started Subsection one

### ISSUE THREAD

**Issue by kuldeep3** [coloredcow-admin/glific-website#14]
![image](https://user-images.githubusercontent.com/37093310/93705368-49059900-fb3a-11ea-94ee-538fa38943fc.png)

**Comment by bohraji** [comment]
@kuldeep3 check the feedbacks below - 

- [ ] The shadow below the section header is missing.
<img width="1239" alt="Screenshot 2020-09-23 at 12 44 13 PM" src="https://user-images.githubusercontent.com/12884297/93979769-5b324200-fd9b-11ea-90fe-db6dead326ce.png">

- [x] Check if the section header needs to be `semi bold`

- [x] The content and alignment of button for the last section is off from the desing.
<img width="361" alt="Screenshot 2020-09-23 at 12 48 23 PM" src="https://user-images.githubusercontent.com/12884297/93979806-6be2b800-fd9b-11ea-93db-ed5da7dea961.png">

- [x] Please confirm if the content for the boxes can be managed from the dashboard. Can we add a new section?

**Comment by kuldeep3** [comment]
@bohraji Yes, the content for boxes, actually whole page content can be managed from the dashboard. Yes, we can add a new section similar to the above ones.

**Comment by kuldeep3** [comment]
@bohraji I think it might be `semi-bold`, but design says it's `regular`. Although it seems to be `semi-bold`, I will change it to `semi-bold`.
![image](https://user-images.githubusercontent.com/37093310/94044637-0965d800-fdec-11ea-8b4a-2bb23676527d.png)

**Comment by bohraji** [comment]
@kuldeep3 the shadow of box title is still not correct. It only appears on the sides and not on the whole width.
