### ISSUE TITLE
Get started subsection 2

### ISSUE THREAD

**Issue by kuldeep3** [coloredcow-admin/glific-website#16]
![image](https://user-images.githubusercontent.com/37093310/93708904-9ba17e00-fb57-11ea-9f1d-55fac155e6df.png)

**Comment by bohraji** [comment]
@kuldeep3 check the feedbacks below - 

- [x] Check the button text alignment and its width.
<img width="1147" alt="Screenshot 2020-09-23 at 12 43 20 PM" src="https://user-images.githubusercontent.com/12884297/93980152-e1e71f00-fd9b-11ea-9218-6345a9de8bde.png">

- [x] The buttons of the boxes should appear at the end on the same line for better asthetics.
<img width="1145" alt="Screenshot 2020-09-23 at 12 43 32 PM" src="https://user-images.githubusercontent.com/12884297/93980240-0216de00-fd9c-11ea-9997-b554f253b2ef.png">

**Comment by kuldeep3** [comment]
@bohraji Button placement in respect of each other looks good to me, suggestions are welcomed.
![image](https://user-images.githubusercontent.com/37093310/94046791-c78a6100-fdee-11ea-9f58-041a91d9b12e.png)

**Comment by bohraji** [comment]
@kuldeep3 the current button alignment changes as per screen, which is not ideal. They both should appear together horizontally. 

Check the contact us page once to see the button alignment.
