### ISSUE TITLE
Homepage :Early Adopters Section

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#18]
Design

![image](https://user-images.githubusercontent.com/30264862/93710843-29389a00-fb67-11ea-898d-bff06f650c57.png)

**Comment by bohraji** [comment]
@mohitgusain check the gap between heading and text on the desktop once, please.
<img width="1547" alt="Screenshot 2020-09-22 at 12 51 57 PM" src="https://user-images.githubusercontent.com/12884297/93853953-7be29500-fcd2-11ea-8df4-1ee75429ee74.png">
