### ISSUE TITLE
Homepage : Know more section

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#20]
Design
![image](https://user-images.githubusercontent.com/30264862/93710976-25594780-fb68-11ea-9171-1adec72ee578.png)

**Comment by bohraji** [comment]
@mohitgusain check the feedbacks below- 

- [x] The borders of the boxes are not as per the design.
<img width="1254" alt="Screenshot 2020-09-22 at 12 53 43 PM" src="https://user-images.githubusercontent.com/12884297/93854304-1c38b980-fcd3-11ea-99bd-2410dc2d5f1f.png">

- [x] The tablet view is not correct. Please check.
<img width="1188" alt="Screenshot 2020-09-22 at 12 55 12 PM" src="https://user-images.githubusercontent.com/12884297/93854326-28247b80-fcd3-11ea-9d6e-70fcd275cee9.png">

- [x] Link missing to tides.
<img width="813" alt="Screenshot 2020-09-22 at 12 55 22 PM" src="https://user-images.githubusercontent.com/12884297/93854345-32467a00-fcd3-11ea-9ff9-6ac92b6134ab.png">

- [ ] Check overall section margin/padding/spacing once.
