### ISSUE TITLE
Search Functionality in FAQ page

### ISSUE THREAD

**Issue by Satendra-SR** [coloredcow-admin/glific-website#21]
- [x]  Add Search functionality in FAQ page.
- [x] There was some change that Is being discussed with Abhishek related to functionality.
    - [x] The search functionality will work on submitting the form.
    - [x] The search icon will go to the rightmost side and work as the submit button.

Designs:
https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/0bWbAj

----
### Updates:
There are some changes that @abhi1203 suggested, sharing it below.
1. Reduce padding to 16px.
2. Add a cross icon
3. Remove the search icon border, the button background will remain the same.

**Comment by bohraji** [comment]
@Satendra-SR check the feedbacks below - 

- [ ] Check with @abhi1203 if these would be a way to remove the filter once it has been added. I had to go back.
- [ ] The Search bar appears differently in different browsers. The border, radius, and alignments are off. Tested on chrome, safari and firefox.
<img width="1129" alt="Screenshot 2020-09-29 at 2 04 04 PM" src="https://user-images.githubusercontent.com/12884297/94534205-bc578b00-025d-11eb-8ef2-59c15512ea27.png">
<img width="1081" alt="Screenshot 2020-09-29 at 2 09 48 PM" src="https://user-images.githubusercontent.com/12884297/94534219-c083a880-025d-11eb-82cc-238e517f4cb9.png">
<img width="1227" alt="Screenshot 2020-09-29 at 2 01 57 PM" src="https://user-images.githubusercontent.com/12884297/94534224-c11c3f00-025d-11eb-9031-a62aabbfaa2e.png">

**Comment by Satendra-SR** [comment]
### Update:
1. Reduce padding to 16px.
2. Add a cross icon
3. Remove the search icon border, the button background will remain the same.

**Comment by Satendra-SR** [comment]
@bohraji the changes are deployed. Please test.

**Comment by bohraji** [comment]
@Satendra-SR this is looking fine.
