### ISSUE TITLE
Page FAQ

### ISSUE THREAD

**Issue by Satendra-SR** [coloredcow-admin/glific-website#22]
- [x] Create a new page FAQ.
- [x] The page header should be dynamic from the dashboard.
- [x] The Faqs will have a collapsable view per the designs below.

### Note:
Exclude the search functionality, that will be handled in #21

https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/0bWbAj

**Comment by Satendra-SR** [comment]
@bohraji this is ready for your testing. Please have a look.
https://glific.coloredcow.com/faq/

**Comment by bohraji** [comment]
@Satendra-SR this is fine. One observation - 
The font colour is not as per the design of the FAQ content. Please check.
<img width="1254" alt="Screenshot 2020-09-23 at 2 16 18 PM" src="https://user-images.githubusercontent.com/12884297/93989535-a5b9bb80-fda7-11ea-848d-0e37737009dd.png">

**Comment by bohraji** [comment]
This is fine. Closing.
