### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by wevekamola** [coloredcow-admin/glific-website#27]
- [ ] Add caldera form support
- [ ] Create Page UI section

**Comment by bohraji** [comment]
@wevekamola check the feedbacks below - 

- [x] Newsletter checkbox is missing.
<img width="1473" alt="Screenshot 2020-09-23 at 1 56 26 PM" src="https://user-images.githubusercontent.com/12884297/93987638-6e4a0f80-fda5-11ea-8a02-4469e830422f.png">

- [x] The input box border is not as per design. Please check.
<img width="1156" alt="Screenshot 2020-09-23 at 1 56 50 PM" src="https://user-images.githubusercontent.com/12884297/93987657-730ec380-fda5-11ea-8c21-afc4ebfafec2.png">

- [x] Input label is incorrect.
<img width="1421" alt="Screenshot 2020-09-23 at 1 57 32 PM" src="https://user-images.githubusercontent.com/12884297/93987707-84f06680-fda5-11ea-9141-0b78150d860d.png">

- [x] The button are of different sizes in design and are dependent on the content size. Please check.
<img width="1382" alt="Screenshot 2020-09-23 at 1 58 16 PM" src="https://user-images.githubusercontent.com/12884297/93987746-90439200-fda5-11ea-82d1-de0b5813ed8d.png">

**Comment by bohraji** [comment]
Also, no email was received on filling up the form

**Comment by wevekamola** [comment]
@bohraji 
- [x] **Newsletter checkbox is missing:** This has been removed after the disscsion with @abhi1203.
- [x] **The input box border is not as per design:** This is now updated as per the design 
- [x] **Input label is incorrect:** This is now updated as per the design 
- [x] **The button are of different sizes in design and are dependent on the content size**: This is now updated as per the design 

On Mail functionality. it's in progress. I have created a ticket for this and tracking it here #54
