### ISSUE TITLE
Mobile view for secondary section - Get started Page

### ISSUE THREAD

**Issue by kuldeep3** [coloredcow-admin/glific-website#29]
![image](https://user-images.githubusercontent.com/37093310/93752875-e6d19480-fc1c-11ea-81ac-5e9dfcf306d1.png)

**Comment by bohraji** [comment]
@kuldeep3 the button looks like they are of the same size. However, on the design, the button is of the same size.
<img width="420" alt="Screenshot 2020-09-23 at 12 56 47 PM" src="https://user-images.githubusercontent.com/12884297/93980631-7cdff900-fd9c-11ea-9cd5-ab25b3551efb.png">

**Comment by kuldeep3** [comment]
@bohraji I think both the buttons would be of the same size, as it shows a pattern in the design, although in the design both buttons have variable width, for now, I am going with the same width to preserve the pattern. Let me know your thoughts on this.

**Comment by bohraji** [comment]
@kuldeep3 all through the site, we have buttons of variable width as the content. Please fix here as well.
