### ISSUE TITLE
Page: Features

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#32]
Design
![image](https://user-images.githubusercontent.com/30264862/93759288-8d229780-fc27-11ea-8201-7ad75103ccd2.png)

**Comment by bohraji** [comment]
@mohitgusain check the feedbacks below - 

- [x] The padding of content inside the box is incorrect. 
<img width="1513" alt="Screenshot 2020-09-23 at 1 28 51 PM" src="https://user-images.githubusercontent.com/12884297/93984362-54a6c900-fda1-11ea-9088-047ebd1d4a06.png">

- [x] Under the demo video section, the video title and `minute` label is missing. Also, check the font size.
<img width="1243" alt="Screenshot 2020-09-23 at 1 28 01 PM" src="https://user-images.githubusercontent.com/12884297/93984437-6d16e380-fda1-11ea-9b8f-2045a9f76f43.png">
