### ISSUE TITLE
Relook the announcement section

### ISSUE THREAD

**Issue by abhi1203** [coloredcow-admin/glific-website#33]
This isn't particularly working well. can you please try something else. maybe bringing the sugn up button closer to the text and then center aligning it. 
![image](https://user-images.githubusercontent.com/16714604/93782940-c8818e00-fc48-11ea-88ba-935e5ef01c4e.png)

The spacing isn't sitting well
![image](https://user-images.githubusercontent.com/16714604/93783037-e51dc600-fc48-11ea-8298-ebbbecad7b7a.png)

**Comment by SunnaMalhotra** [comment]
Check Sketch cloud please, I made a few changes @abhi1203

**Comment by abhi1203** [comment]
Maybe this:
![image](https://user-images.githubusercontent.com/16714604/93848417-2654bb00-fcc7-11ea-84ba-6026500ad575.png)

I mean the color can still be green for contrast
