### ISSUE TITLE
Homepage : Contact form

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#39]
Design
![image](https://user-images.githubusercontent.com/30264862/93851695-38862780-fcce-11ea-9e8a-a7e2ca32ca05.png)

**Comment by mohitgusain** [comment]
This issue is related to this #27 issue.  It will come on the homepage after the contact page will have been deployed

**Comment by bohraji** [comment]
@mohitgusain this is now available on the website. Please update it.
