### ISSUE TITLE
SMTP Credentials for mails

### ISSUE THREAD

**Issue by wevekamola** [coloredcow-admin/glific-website#43]
We need SMTP credetials for the website to send secure mails.

**Comment by bohraji** [comment]
Create two accounts - info@glific.org and archive@glific.org
Use the info one to send emails

**Comment by bohraji** [comment]
@mohitgusain who is monitories these? Can you create a document with the link and credentials. We can hand them over to the Glific team

**Comment by bohraji** [comment]
@mohitgusain please share the link of the doc. If done, please close this issue out. Better not share the credentials publically

**Comment by mohitgusain** [comment]
@bohraji , Yes credentials already shared with @SunnaMalhotra and @abhi1203 . Closing it now.
