### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#45]
Design
![image](https://user-images.githubusercontent.com/30264862/93980178-e90e2d00-fd9b-11ea-9670-68b7a6905506.png)

**Comment by bohraji** [comment]
Looks fine.
@SunnaMalhotra @abhi1203 please get the photographs of other team members and provide it here. You can use discord for ot

**Comment by SunnaMalhotra** [comment]
@bohraji I just checked, both Anshul and Dignesh don't have their pictures on discord

**Comment by SunnaMalhotra** [comment]
and who else is to be added to the team?

**Comment by bohraji** [comment]
@SunnaMalhotra we can ask them for the details. Also please add Sanjeev too.

**Comment by SunnaMalhotra** [comment]
Sanjeev specifically asked to be removed from the teams page @bohraji

**Comment by SunnaMalhotra** [comment]
Images have been sent to me by both of them and now can be updated on the website.
![Anshul](https://user-images.githubusercontent.com/71515238/94628702-4ba48300-02de-11eb-9e91-7268ecaca6cd.jpg)
![Ad](https://user-images.githubusercontent.com/71515238/94628713-565f1800-02de-11eb-8cde-80256a7303f3.jpg)

**Comment by mohitgusain** [comment]
@SunnaMalhotra, Can you please provide the resize version of this image, as they are bigger.
