### ISSUE TITLE
Clarification on footer links

### ISSUE THREAD

**Issue by bohraji** [coloredcow-admin/glific-website#47]
@SunnaMalhotra @abhi1203 please provide details on the pages on these links in footer
<img width="1494" alt="Screenshot 2020-09-23 at 2 10 11 PM" src="https://user-images.githubusercontent.com/12884297/93988881-dd743380-fda6-11ea-9794-9726693b65f7.png">

**Comment by SunnaMalhotra** [comment]
How it works will be linked to How It works page on the Glific Website itself. Demo videos will be linked to our YouTube channel. Discussion Forum is supposed to be linked to our Discord but how to link and add that is still unclear to me. Case studies can be blank for now, we will add a link when we write a few case studies about the NGO's that are using the platform.

**Comment by abhi1203** [comment]
@SunnaMalhotra We also have a page for demo videos on website - can we link to that please?
@bohraji for discussion forum can we add the same discord link added to the icon here, or maybe we can remove since it's redundant
Yeah we dont have a case studies page right now

**Comment by bohraji** [comment]
@SunnaMalhotra Please provide the link to the how it works page. Unable to find it.

**Comment by SunnaMalhotra** [comment]
Oh, I apologise. the page it will be connected to will be the Get started page. And 'how it works' in the footer will also be changed to 'get started'

**Comment by SunnaMalhotra** [comment]
oh and @bohraji the demo videos link in the footer will take them to the demo video section on the features page. It's the topmost section on the features page.

**Comment by bohraji** [comment]
Summing up the discussion above  - 

- [x] Rename `How it works` to `Get started`. Link to the related page.
- [x] Remove `Discussion Forum` and `Case Studies`
- [x] Link `Demo Videos` to `Features page`
