### ISSUE TITLE
Performance fixes for the the site

### ISSUE THREAD

**Issue by bohraji** [coloredcow-admin/glific-website#48]
<img width="1404" alt="Screenshot 2020-09-23 at 2 21 22 PM" src="https://user-images.githubusercontent.com/12884297/93990013-38f2f100-fda8-11ea-988b-e307922ef180.png">

**Comment by mohitgusain** [comment]
@bohraji , i have taken the major steps to improve the performance, but it seems like this is something which also relies on the hosting which is dependent on the Jetpack plugin. Along with it there is youtube embedded video is loading that's why the page performance is slow

**Comment by bohraji** [comment]
Good for now. Closing.
