### ISSUE TITLE
Default image for posts

### ISSUE THREAD

**Issue by wevekamola** [coloredcow-admin/glific-website#52]
We need to add a default image if the post doesn't have any featured image.

<img width="599" alt="Screenshot 2020-09-24 at 5 40 27 PM" src="https://user-images.githubusercontent.com/29367838/94143251-328a7500-fe8d-11ea-9d00-1b042085d891.png">

**Comment by SunnaMalhotra** [comment]
I have uploaded an SVG and the PDF in the drive.
here is the Link to that folder.
https://drive.google.com/drive/folders/12U6Gw9bYgV2R9ciVyDB1mWaiS755-gF1?usp=sharing

**Comment by wevekamola** [comment]
@bohraji This is completed. closing it
