### ISSUE TITLE
Book a Demo Link

### ISSUE THREAD

**Issue by bohraji** [coloredcow-admin/glific-website#58]
@abhi1203 @SunnaMalhotra please share where the `Book a demo` page will lead the user to?

**Comment by abhi1203** [comment]
@bohraji im thinking we'll just collect their email ids for now? so maybe a popup asking for their name, ngo name and email id.
we can integrate a calendar for mark their times later.

**Comment by bohraji** [comment]
@abhi1203 @SunnaMalhotra we will need the design of this popup. Please provide by tomorrow.

**Comment by SunnaMalhotra** [comment]
Yes, I will work on that and share it @bohraji

**Comment by SunnaMalhotra** [comment]
I have updated the Sketch cloud with the pop-up designs.
here is the cloud link: https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/qqdb7y. Designed for all three screen Phone, Tablet & Dekstop.

**Comment by bohraji** [comment]
This is looking fine. Closing.
