### ISSUE TITLE
Tides logo svg image

### ISSUE THREAD

**Issue by abhi1203** [coloredcow-admin/glific-website#59]
![image](https://user-images.githubusercontent.com/16714604/94279089-44d9e100-ff69-11ea-8d13-af353a5eaf87.png)
@SunnaMalhotra can you also upload an svg image for tides on the drive and share it with mohit?

**Comment by SunnaMalhotra** [comment]
https://drive.google.com/drive/folders/12U6Gw9bYgV2R9ciVyDB1mWaiS755-gF1?usp=sharing This is link to the drive where the tides SVG has been uploaded. The SVGs have been previously shared with Mohit as well.
