### ISSUE TITLE
Gifs fixes

### ISSUE THREAD

**Issue by abhi1203** [coloredcow-admin/glific-website#60]
- [ ] Let's not blur these images plus, let's show only one instead of a cluster of 4. im not sure if glific supports that. you can test this out before finalising
![image](https://user-images.githubusercontent.com/16714604/94294157-0b12d580-ff7d-11ea-8eb8-7fb029de764c.png)

- [ ] correct the text alignment in the button
![image](https://user-images.githubusercontent.com/16714604/94294223-254cb380-ff7d-11ea-9a53-93e1f16b4c53.png)

- [ ] correct the font style in both the messages
![image](https://user-images.githubusercontent.com/16714604/94294271-31d10c00-ff7d-11ea-9739-b34a145b306b.png)

- [ ] correct the tag alignment **(wherever applicable)**
![image](https://user-images.githubusercontent.com/16714604/94294492-8aa0a480-ff7d-11ea-8b5e-05327b097139.png)

- [ ] correct the spacing of text inside the message box
![image](https://user-images.githubusercontent.com/16714604/94294519-942a0c80-ff7d-11ea-9a21-78d454af8970.png)

- [ ] add emoji next to glific in the message in tags gif
![image](https://user-images.githubusercontent.com/16714604/94294641-bb80d980-ff7d-11ea-9917-e893fd8a0ca4.png)

- [ ] correct the spelling of hindi in the message written in hindi  **(wherever applicable)**

- [ ] correct the middle alignment of speed sends and templates text 
![image](https://user-images.githubusercontent.com/16714604/94294858-10245480-ff7e-11ea-9e17-d852c25ab518.png)

- [ ] use real text instead of lorem ipsum
![image](https://user-images.githubusercontent.com/16714604/94294922-26321500-ff7e-11ea-89c3-58b9f6bc5dd9.png)

- [ ] the audio should play from the start since it seems like the message is just being sent
![image](https://user-images.githubusercontent.com/16714604/94294960-321dd700-ff7e-11ea-9bba-43e0f52b9a9a.png)

- [ ] Can we do something about the flickering outlines overall

- [ ] please update emojis everywhere
![image](https://user-images.githubusercontent.com/16714604/94295129-6a251a00-ff7e-11ea-80c1-6335c4a89e86.png)

- [ ]

**Comment by SunnaMalhotra** [comment]
https://drive.google.com/drive/folders/1UFE_oYbh766UGsihigF0mxiSPpkZKxv3?usp=sharing
Here all the 8 GIFs for the Features page. These GIFs are to be replaced with the images on that page.
