### ISSUE TITLE
Single Blog Page 

### ISSUE THREAD

**Issue by wevekamola** [coloredcow-admin/glific-website#67]
- Single Page UI
- Social media Share
- Comment Box
- Recommend Reading

**Comment by wevekamola** [comment]
@bohraji Ready for testing

**Comment by bohraji** [comment]
@wevekamola check the feedbacks from testing below. Most of the flow is working fine. Feedback are on the comments section.

- [x] Can we have a captcha on the form?

- [x] The form submits for the required field. Front end validation is missing.

- [x] Once the form submits with incomplete information, then we get an error page from WordPress.
<img width="1231" alt="Screenshot 2020-09-29 at 12 02 25 PM" src="https://user-images.githubusercontent.com/12884297/94522681-a3df7480-024d-11eb-9cbf-4971ec5cf72a.png">

**Comment by wevekamola** [comment]
@bohraji All the feedback is implemented. Ready to test.

**Comment by bohraji** [comment]
@wevekamola all items are looking fine. The email field does not validate for type email. Can we add that?

**Comment by wevekamola** [comment]
@bohraji @abhi1203 Guys as the site is hosted on the Wordpress hosting. They provide a feature called jetpack which overwrites the default comment section and all the functionality is also managed by them. On the production blog page, this has overwritten our UI changes.

<img width="1129" alt="Screenshot 2020-10-06 at 5 14 19 PM" src="https://user-images.githubusercontent.com/29367838/95197789-c34f4200-07f7-11eb-81f6-2fd14d40a3bc.png">

**Comment by abhi1203** [comment]
@wevekamola this means we have to live with these unwanted changes? or is there a way around?

**Comment by wevekamola** [comment]
@abhi1203 The workaround will be a bit tricky and will require a lot of effort to redesign the one we have on production as in UAT we don't have this issue. If the live site UI doesn't look too much out of space I'll recommend letting it be like this.

**Comment by abhi1203** [comment]
Sure, recommendation has been taken. @wevekamola thanks

**Comment by wevekamola** [comment]
@abhi1203 Thanks.

**Comment by bohraji** [comment]
Closing.
