### ISSUE TITLE
Platform Testing : Homepage (sunna)

### ISSUE THREAD

**Issue by SunnaMalhotra** [coloredcow-admin/glific-website#72]
#71

**Comment by SunnaMalhotra** [comment]
<img width="1419" alt="Screenshot 2020-09-29 at 3 48 06 PM" src="https://user-images.githubusercontent.com/71515238/94546280-48bc7a80-026b-11eb-95f5-0c82e9c3be09.png">
The announcement bar is a dynamic link, the text and the functionality of this bar depends on the what we wish to announce about Glific.

**Comment by SunnaMalhotra** [comment]
### Announcement Bar
The Announcement bar is a dynamic link, the text and the functionality of this bar depends on the what we wish to announce about Glific.
<img width="1349" alt="Screenshot 2020-09-29 at 5 31 20 PM" src="https://user-images.githubusercontent.com/71515238/94555772-b53e7600-0279-11eb-9835-3cb02d9662cf.png">

- [ ] The **Sign up button** when clicked, takes us to the homepage. There needs to be an input field to redirect the users to a google form which they can fill up to Sign up to the webinar. 

<img width="203" alt="Screenshot 2020-09-29 at 3 51 18 PM" src="https://user-images.githubusercontent.com/71515238/94546592-bb2d5a80-026b-11eb-8333-f69bb1d4decc.png">

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
### TopBar Issues
Check the link to the TopBar menu symbol on the sketch document here - https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/GVd7JY
- [ ] 1. The **Glific Logo** in only the **Desktop version** is quite big, thus making the TopBar too thick.

<img width="1424" alt="Screenshot 2020-09-29 at 4 07 12 PM" src="https://user-images.githubusercontent.com/71515238/94548186-f761ba80-026d-11eb-9ce3-51cfecd1a1ec.png">

- The height in the sketch document for the Logo is 85w x 52h. the Total Height of the Topbar in the Desktop version is 80px.

- [ ] 2. **Book a demo button missing** from the **TopBar in the Phone & Tablet version**

<img width="556" alt="Screenshot 2020-09-29 at 4 58 49 PM" src="https://user-images.githubusercontent.com/71515238/94552830-29c2e600-0275-11eb-9a94-dedad0e349c4.png">

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
### Button Placement and functions

- [ ] 1. The **Book a demo** and **Talk to us Buttons** in the **Tablet and Phone version** are supposed to be left aligned and one under the other. Please refer to the homepage on the Sketch cloud (https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/wgj4YA)
<img width="573" alt="Screenshot 2020-09-29 at 4 21 05 PM" src="https://user-images.githubusercontent.com/71515238/94549481-eb76f800-026f-11eb-88be-a725f8ce9e4f.png">
<img width="888" alt="Screenshot 2020-09-29 at 4 20 58 PM" src="https://user-images.githubusercontent.com/71515238/94549488-f03bac00-026f-11eb-8a31-f1c88d098886.png">
- This is how it is in the sketch file.
<img width="681" alt="Screenshot 2020-09-29 at 4 23 53 PM" src="https://user-images.githubusercontent.com/71515238/94549735-490b4480-0270-11eb-8fa2-d59ce6f76a29.png">

- [ ] 2. The **Talk to us Button** links to the Contact Page.

- [ ] 3. The Book a demo Button opens up a pop-up on the homepage itself to allow the users to Book a demo from right there. I have provided the Design for this. #58 
Here is the design file for this page as well- https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/qqdb7y

**Comment by SunnaMalhotra** [comment]
### Update Illustration on the Homepage 
Please refer to the homepage on the Sketch cloud (https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/wgj4YA)

- [ ] 1.  Update Illustration for **Enable communications at scale** in the **Why Glific** section of the Homepage. 
<img width="556" alt="Screenshot 2020-09-29 at 4 31 38 PM" src="https://user-images.githubusercontent.com/71515238/94550454-5d9c0c80-0271-11eb-9c45-40d0a6e8ba29.png">
- This is what it looks like in the sketch file.
<img width="556" alt="Screenshot 2020-09-29 at 4 32 54 PM" src="https://user-images.githubusercontent.com/71515238/94550562-8c19e780-0271-11eb-9953-da8a0ee4cf7f.png">

- [ ] 2. Update Illustration for **Analytic and Report** in the **Key features** section of the Homepage 
<img width="842" alt="Screenshot 2020-09-29 at 5 46 16 PM" src="https://user-images.githubusercontent.com/71515238/94557393-1ff0b100-027c-11eb-95c8-5d8224114d04.png">
- This is how it looks on Sketch 
<img width="149" alt="Screenshot 2020-09-29 at 5 53 14 PM" src="https://user-images.githubusercontent.com/71515238/94557882-cb016a80-027c-11eb-9489-007643efa789.png"> 

### *** ( important )
- [ ] 3. Update Illustration on the section 1 of the Homepage. The image is to be Horizontally mirrored to make space for the Buttons.
<img width="345" alt="Screenshot 2020-09-29 at 5 56 08 PM" src="https://user-images.githubusercontent.com/71515238/94558126-2c293e00-027d-11eb-808c-472cc10d828b.png">
- This is how it looks on the sketch Document
<img width="345" alt="Screenshot 2020-09-29 at 5 55 47 PM" src="https://user-images.githubusercontent.com/71515238/94558239-53800b00-027d-11eb-9fa3-1e75b5b75066.png">

**Comment by SunnaMalhotra** [comment]
**Book a demo button** missing from the **TopBar in the Phone & Tablet version**

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
### Remove Button
- [ ] The **View all case studies button** in the **Early Adopters** section of the homepage is to be removed as we do not have any Case studies as of now.
<img width="476" alt="Screenshot 2020-09-29 at 6 00 01 PM" src="https://user-images.githubusercontent.com/71515238/94558618-b83b6580-027d-11eb-8ad2-d64c6bd53ab2.png">

**Comment by SunnaMalhotra** [comment]
### Placement Issue in the section under Early adopters
Please refer to the homepage on the Sketch cloud (https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/wgj4YA)

- [ ] 1. Only in the **Tablet Version** the **Open Source section isn't consistent**. 
<img width="917" alt="Screenshot 2020-09-29 at 6 06 46 PM" src="https://user-images.githubusercontent.com/71515238/94559553-0c931500-027f-11eb-9db0-3ee04dae4b6e.png">
- This is how it looks in the Sketch document.
<img width="355" alt="Screenshot 2020-09-29 at 6 11 08 PM" src="https://user-images.githubusercontent.com/71515238/94559716-449a5800-027f-11eb-857f-1d0009f5016a.png">

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
### Text correction in the Footer

- [ ] In the **Tablet and phone version** of the **footer**. There is a **single space before the word ColoredCow** thus making the text seem like it's not aligned within itself.
<img width="88" alt="Screenshot 2020-09-29 at 6 17 01 PM" src="https://user-images.githubusercontent.com/71515238/94560311-16694800-0280-11eb-838a-3934f6046051.png">

**Comment by SunnaMalhotra** [comment]
### Text change

- [ ] **Company name tex**t to be changed to **organisation name**

<img width="704" alt="Screenshot 2020-09-30 at 1 20 47 PM" src="https://user-images.githubusercontent.com/71515238/94658003-df4a7380-031f-11eb-976a-9cd43b2ee46a.png">

**Comment by mohitgusain** [comment]
> ### Announcement Bar
> The Announcement bar is a dynamic link, the text and the functionality of this bar depends on the what we wish to announce about Glific.
> <img alt="Screenshot 2020-09-29 at 5 31 20 PM" width="1349" src="https://user-images.githubusercontent.com/71515238/94555772-b53e7600-0279-11eb-9835-3cb02d9662cf.png">
> 
> * [ ]  The **Sign up button** when clicked, takes us to the homepage. There needs to be an input field to redirect the users to a google form which they can fill up to Sign up to the webinar.
> 
> <img alt="Screenshot 2020-09-29 at 3 51 18 PM" width="203" src="https://user-images.githubusercontent.com/71515238/94546592-bb2d5a80-026b-11eb-8333-f69bb1d4decc.png">

@SunnaMalhotra , Announcement bar text and link both are dynamic and changeable from the dashboard. We don't have the link for google form that's why it is redirecting to the homepage. If you can provide that link, I can put it. Please let me know if any other way, I can help you to test this feature.

**Comment by SunnaMalhotra** [comment]
Oh alright!! I apologise I wasn't aware of that. Yes, I shall provide a link as soon as I get one. @mohitgusain

**Comment by SunnaMalhotra** [comment]
### Problem in the links in the footer

- [ ] 1.The resources links of Blogs and webinar in the footer aren't linked to their respective links. when clicked they open the Homepage again. 
- [ ] 2. The YouTube link isn't connected to our YouTube channel. It reloads the homepage.

<img width="222" alt="Screenshot 2020-09-30 at 4 12 53 PM" src="https://user-images.githubusercontent.com/71515238/94675814-f5fcc480-0337-11eb-893f-ed09d6fd926b.png">

@mohitgusain

**Comment by mohitgusain** [comment]
> ### Problem in the links in the footer
> * [ ]  1.The resources links of Blogs and webinar in the footer aren't linked to their respective links. when clicked they open the Homepage again.
> * [ ]  2. The YouTube link isn't connected to our YouTube channel. It reloads the homepage.
> 
> <img alt="Screenshot 2020-09-30 at 4 12 53 PM" width="222" src="https://user-images.githubusercontent.com/71515238/94675814-f5fcc480-0337-11eb-893f-ed09d6fd926b.png">
> 
> @mohitgusain

@SunnaMalhotra can you please provide the Youtube link, where it will redirect

**Comment by SunnaMalhotra** [comment]
Glific's YouTube channel-https://www.youtube.com/channel/UCIJfQhrbJSCWQtzdI484nng
@mohitgusain

**Comment by mohitgusain** [comment]
@SunnaMalhotra Your testing feedbacks implemented. Please have a look.

**Comment by SunnaMalhotra** [comment]
All the changes have been implemented and done except this one. We need to flip the image horizontally to fit the buttons better. @mohitgusain 
<img width="350" alt="Screenshot 2020-10-01 at 9 40 27 AM" src="https://user-images.githubusercontent.com/71515238/94767572-59cfcd80-03ca-11eb-97fa-e018f13634f7.png">

**Comment by mohitgusain** [comment]
@SunnaMalhotra , Image has been changed. Please have a look now

**Comment by SunnaMalhotra** [comment]
Yes, all changes in the homepage have been made
