### ISSUE TITLE
Platform Testing: Features Page (sunna)

### ISSUE THREAD

**Issue by SunnaMalhotra** [coloredcow-admin/glific-website#73]
#71

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
### Placement Issue in the Latest Demo Video Section
See the Features page on the Sketch cloud document here - https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/4z5pmx

- [x] 1. The other videos on the right side of this section are too clustered.
<img width="1053" alt="Screenshot 2020-09-30 at 3 36 03 AM" src="https://user-images.githubusercontent.com/71515238/94621829-a9c96a00-02ce-11eb-80e1-71468021aad1.png">

-  Two videos to be visible at a single time and the rest can be looked at by scrolling down, in the **Desktop & Tablet version**, The phone version is fine.

- The name of those videos is not visible in the **Desktop & Tablet version**, The phone version is fine.
, but ones we remove the third video there will be place for the names.

- The **Latest demo Video** text is not similar to the sketch file in all the versions. ( The font details are - Heebo, Medium, 24, colour HEX code-#3B3B3B )

This is how the sketch file looks
<img width="370" alt="Screenshot 2020-09-30 at 3 48 29 AM" src="https://user-images.githubusercontent.com/71515238/94622498-f19cc100-02cf-11eb-9de6-955945da39a3.png">

**Comment by SunnaMalhotra** [comment]
### Spacing Issue in the Features section 
See the features page on Sketch Document here-https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/4z5pmx

- [x] 1.  Top and bottom spacing in the features section in **Create groups both automatically and manually** is not equal. In the **tablet & desktop version** 
<img width="475" alt="Screenshot 2020-09-30 at 3 52 30 AM" src="https://user-images.githubusercontent.com/71515238/94622800-7daee880-02d0-11eb-837b-3dba6d8e58c7.png">

- [x] 2.  Top and bottom spacing in the features section in **Multiple language support** is not equal. In the **tablet & desktop version** 
<img width="475" alt="Screenshot 2020-09-30 at 3 53 29 AM" src="https://user-images.githubusercontent.com/71515238/94622895-a20ac500-02d0-11eb-8693-080ebf806fcd.png">

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
#60 

- [x] Update GIFs on the Features page.

Find all the 8 GIFs on the drive link here - https://drive.google.com/drive/folders/1UFE_oYbh766UGsihigF0mxiSPpkZKxv3?usp=sharing

<img width="247" alt="Screenshot 2020-09-30 at 3 57 41 AM" src="https://user-images.githubusercontent.com/71515238/94623165-3543fa80-02d1-11eb-89aa-5915e66a53cc.png">

**Comment by mohitgusain** [comment]
@SunnaMalhotra  Feedback implemented. Please have a look

**Comment by SunnaMalhotra** [comment]
- [x] The images attached to the video title could be the same as they are on YouTube.

- [x] Fix the name of the Videos, both the main one and on the sides

- [x] Check the timestamps of the Video

- V0.3 - 5:47

- V0.2 - 5:30

- V0.1 - 5:55

<img width="888" alt="Screenshot 2020-10-01 at 2 18 25 PM" src="https://user-images.githubusercontent.com/71515238/94788571-61ef3380-03f1-11eb-98f7-d732490caa34.png">

@mohitgusain

**Comment by mohitgusain** [comment]
@SunnaMalhotra The name and the time has been fixed. Have a look now

**Comment by SunnaMalhotra** [comment]
Alright
