### ISSUE TITLE
Platform Testing: Get started page (sunna)

### ISSUE THREAD

**Issue by SunnaMalhotra** [coloredcow-admin/glific-website#74]
#71

**Comment by SunnaMalhotra** [comment]
### Problem with the 03 pointer on Get started Page  
check the Get Started page on the sketch cloud document here- https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/Ov3g98

- [x] 1. A bullet point is added to the 03 pointer on the get started page in all the versions of the website Phone, Tablet & Desktop. 

<img width="721" alt="Screenshot 2020-09-30 at 4 06 26 AM" src="https://user-images.githubusercontent.com/71515238/94623696-6e309f00-02d2-11eb-961c-4040ed0f37a6.png">

- The bullet point is to be removed and the text is to be left aligned to the  sub-heading.

this is how it looks on the sketch file.
<img width="480" alt="Screenshot 2020-09-30 at 4 11 45 AM" src="https://user-images.githubusercontent.com/71515238/94624013-2bbb9200-02d3-11eb-92b7-d95e1daa05d5.png">

**Comment by SunnaMalhotra** [comment]
### Re-allign the buttons in the last section if the Get started page

- [ ] The button placement isn't looking as well as I had anticipated. If possible, could these be left aligned to the text and then we can have equal spacing on left and right. Even in the sketch document it looks like this.

<img width="706" alt="Screenshot 2020-09-30 at 4 14 17 AM" src="https://user-images.githubusercontent.com/71515238/94624209-8654ee00-02d3-11eb-830b-fd104c93e7bf.png">

**Comment by SunnaMalhotra** [comment]
Text alignment issue in the 02 pointer on the Get started page 
Check the Get started page on the sketch cloud here -https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/Ov3g98

- [x] 1. The **know mor**e text in green isn't left aligned with the text above in the first bullet pointer. In the **Phone version** 

<img width="252" alt="Screenshot 2020-09-30 at 4 17 49 AM" src="https://user-images.githubusercontent.com/71515238/94624407-067b5380-02d4-11eb-98ba-8ea25eb646a7.png">

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
### The link needs to be updated/added

- [ ] 1. It shows page not found when the Docx link is clicked. @abhi1203 could you please provide the correct link

<img width="721" alt="Screenshot 2020-09-30 at 4 21 13 AM" src="https://user-images.githubusercontent.com/71515238/94624628-80134180-02d4-11eb-9971-db9f52cdc225.png">


- [x] 2. where would these links be redirected?
<img width="694" alt="image" src="https://user-images.githubusercontent.com/71515238/94625181-c026f400-02d5-11eb-8b5d-fe5f6ed8469f.png">

- [ ] 3. @abhi1203 would require a redirecting link for this as well
<img width="338" alt="Screenshot 2020-09-30 at 4 31 47 AM" src="https://user-images.githubusercontent.com/71515238/94625268-f82e3700-02d5-11eb-8b87-c4534d45e760.png">

**Comment by SunnaMalhotra** [comment]
### Links for this section

@abhi1203, Where would these links be re-directed?
<img width="694" alt="Screenshot 2020-09-30 at 4 24 15 AM" src="https://user-images.githubusercontent.com/71515238/94624806-ebf5aa00-02d4-11eb-948e-e2e4794d5f3d.png">

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
- [x] This part from the last section of this page to be removed
 As we do not have any case studies as of now, we can remove this part

<img width="338" alt="Screenshot 2020-09-30 at 4 26 29 AM" src="https://user-images.githubusercontent.com/71515238/94624942-3bd47100-02d5-11eb-8f3c-0802a91ee775.png">

The **Want to know about the new features that are in the upcoming versions of Glific?** part can be centre aligned to the page.
<img width="678" alt="Screenshot 2020-09-30 at 4 28 22 AM" src="https://user-images.githubusercontent.com/71515238/94625061-7f2edf80-02d5-11eb-99c7-a1268a43c22f.png">

**Comment by kuldeep3** [comment]
@SunnaMalhotra The feedbacks looks good. I have a question on the bullet point, will there be no bullet point for the third section, as the other two sections have bullet point. What if there are more than three sections, will there be a bullet point for them or not?

**Comment by SunnaMalhotra** [comment]
Yes, there will be no bullet point in the third section. In the future if any more sections are added and they happen to have more than one pointer within them then we can add bullet points. @kuldeep3

**Comment by mohitgusain** [comment]
@SunnaMalhotra This is ready for the test. Please have a look.

**Comment by SunnaMalhotra** [comment]
Just the links that abhishek gave need to be added.

Let's use this link for facebook business verfication https://www.facebook.com/business/help/2058515294227817?id=180505742745347

and this one for gupshup account creation: https://www.gupshup.io/developer/home

@mohitgusain

**Comment by mohitgusain** [comment]
@SunnaMalhotra these link has been updated now. Please have a look now

**Comment by SunnaMalhotra** [comment]
- [ ] The previous link to be changed to the text **See document** and a link for the doc is to be added to that text, so when the user clicks see document then the doc open up. 
link- https://docs.google.com/document/d/1CQAFkDsktgk-2dUb_qOkeVZyLuObCyBql5wI3V3kT2E/edit

<img width="729" alt="Screenshot 2020-10-01 at 4 40 53 PM" src="https://user-images.githubusercontent.com/71515238/94802289-0038c480-0405-11eb-83cb-002df4d7cdad.png">

This is how it would look
<img width="729" alt="Screenshot 2020-10-01 at 4 44 30 PM" src="https://user-images.githubusercontent.com/71515238/94802544-8228ed80-0405-11eb-8f35-ce7faa10de5d.png">


- [ ] This **link to be added** to the **Visit our docs button**

link- https://docs.google.com/document/d/1Q7ozYAHl1wcVQlXcg3iZjQZPHaUQJzQCYHTLaajncrs/edit
<img width="349" alt="Screenshot 2020-10-01 at 4 47 03 PM" src="https://user-images.githubusercontent.com/71515238/94802776-db911c80-0405-11eb-8c5d-dbf0c14d2524.png">
@mohitgusain
