### ISSUE TITLE
Platform Testing: Resources page (sunna)

### ISSUE THREAD

**Issue by SunnaMalhotra** [coloredcow-admin/glific-website#75]
#71

**Comment by SunnaMalhotra** [comment]
### Button Alignment in the single blog page
check the single blogs page on the sketch cloud here -https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/DRD2d4

- [ ] 1. The **Back to blogs** button isn't to be aligned to the text above in the **Phone & tablet** version 

<img width="338" alt="Screenshot 2020-09-30 at 4 42 02 AM" src="https://user-images.githubusercontent.com/71515238/94625855-66bfc480-02d7-11eb-81f9-7d6004178277.png">

**Comment by SunnaMalhotra** [comment]
- [x] **Leave a reply text** in that section is to be **replaced with Post a comment** and for it to be in the Glific Dark green colour.

- [x] **Company name text** to be changed to **organisation name**

<img width="902" alt="Screenshot 2020-09-30 at 4 43 43 AM" src="https://user-images.githubusercontent.com/71515238/94625967-a4245200-02d7-11eb-9d34-32ee1730939d.png">

**Comment by SunnaMalhotra** [comment]
### Wrong button placement in the last section of the blogs page.
Check out the Blogs resources page on the sketch cloud document here- https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/mVgG8P

- [x] 1. the View Discord buttonis to be centre aligned with the View Github button in the **Tablet** version 

<img width="628" alt="Screenshot 2020-09-30 at 4 46 09 AM" src="https://user-images.githubusercontent.com/71515238/94626096-fb2a2700-02d7-11eb-82c0-85015223d079.png">

This is how it looks like in the sketch document.
<img width="365" alt="Screenshot 2020-09-30 at 4 50 59 AM" src="https://user-images.githubusercontent.com/71515238/94626395-a6d37700-02d8-11eb-93f1-b6cb0325f6f3.png">

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
### Spacing issue in the Sign up for newsletter section
Check out the Blogs resources page on the sketch cloud document here- https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/mVgG8P

- [x] 1. Similar issue in all the versions of the website Phone, tablet & desktop.
<img width="797" alt="Screenshot 2020-09-30 at 4 52 47 AM" src="https://user-images.githubusercontent.com/71515238/94626539-e7cb8b80-02d8-11eb-9625-1760493e596f.png">

this is what it looks like in the sketch document.
<img width="361" alt="Screenshot 2020-09-30 at 4 54 07 AM" src="https://user-images.githubusercontent.com/71515238/94626617-177a9380-02d9-11eb-89d1-6b16edd47e9b.png">

- [ ] 2. The sign up button text is different from the other button texts. 
<img width="361" alt="Screenshot 2020-09-30 at 4 56 34 AM" src="https://user-images.githubusercontent.com/71515238/94626795-6e806880-02d9-11eb-9ad2-16cab2d311c9.png">
The button Text info is- Heebo, 18, Bold with 32px horizontal spacing and 8px vertical spacing from the text and the box.

**Comment by SunnaMalhotra** [comment]
### *** ( Important )
### Problems with the Webinar Page
Check the webinar page on the sketch document here -https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/aK0lYv

- [x] The other videos on the Webinar page is very different from what the designs show. In the design aspect it is similar to the demo videos section on the features page. 
<img width="872" alt="Screenshot 2020-09-30 at 4 59 25 AM" src="https://user-images.githubusercontent.com/71515238/94626951-d5058680-02d9-11eb-81d8-1a9a99c46050.png">

- Also now if we have done two webinars we can add them both here, or if the second one is not on YouTube yet then we can link the first webinar here.

This is how it looks on the sketch document.
<img width="456" alt="Screenshot 2020-09-30 at 5 02 35 AM" src="https://user-images.githubusercontent.com/71515238/94627106-45aca300-02da-11eb-9946-f4d6333cfb0d.png">

This is happening on safari

**Comment by SunnaMalhotra** [comment]
check the FAQ page on the sketch document here- https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/Aywodz

- [x] Problem with the Search bar in the FAQ page.
<img width="456" alt="Screenshot 2020-09-30 at 5 03 55 AM" src="https://user-images.githubusercontent.com/71515238/94627182-768cd800-02da-11eb-95a9-aa138a845401.png">

This is how it looks in the sketch document
<img width="287" alt="Screenshot 2020-09-30 at 5 04 51 AM" src="https://user-images.githubusercontent.com/71515238/94627248-96bc9700-02da-11eb-8ef6-49b8d4c41d11.png">

**Comment by Satendra-SR** [comment]
@bohraji @mohitgusain @SunnaMalhotra there was some discussion and changes in the FAQ page. I've listed all the changes in the related issue. Have a look here https://github.com/coloredcow-admin/glific-website/issues/21

**Comment by wevekamola** [comment]
@bohraji @SunnaMalhotra @mohitgusain 

For the mentioned issue:

`Leave a reply text in that section is to be replaced with Post a comment`

As we are using the wordpress default comment box for publishing the comments on the single blog page. There has been some limitation. We can't change the title of the Comment box for now. I have already discussed it with the @abhi1203.

**Comment by kuldeep3** [comment]
@SunnaMalhotra To be clear about the webinar page, it only accepts `youtube links` for now. So, if there are no `youtube link` for the video, the video can't be visible on the page. Overall feedback looks good to me.

**Comment by SunnaMalhotra** [comment]
Here is the Link to our first webinar- https://www.youtube.com/watch?v=jC5lUahxYKM&t=114s
Second webinar- https://www.youtube.com/watch?v=Z1vvASeLb0w

We can add these two videos for now and keep the rest empty. We will add more as they come along. @kuldeep3

**Comment by mohitgusain** [comment]
@SunnaMalhotra This issue is ready for your testing. Please have a look

**Comment by SunnaMalhotra** [comment]
- [ ] The webinar page need relevant titles, images and timestamps.

<img width="888" alt="Screenshot 2020-10-01 at 2 28 44 PM" src="https://user-images.githubusercontent.com/71515238/94789436-88fa3500-03f2-11eb-93cc-021393a91dba.png">

This is how it looks on YouTube
<img width="221" alt="Screenshot 2020-10-01 at 2 29 30 PM" src="https://user-images.githubusercontent.com/71515238/94789524-a4654000-03f2-11eb-90c7-b827c4cc5dc3.png">
<img width="221" alt="Screenshot 2020-10-01 at 2 30 10 PM" src="https://user-images.githubusercontent.com/71515238/94789601-bba42d80-03f2-11eb-9f10-34d27dac814c.png">
@mohitgusain @kuldeep3

**Comment by SunnaMalhotra** [comment]
- [ ] And the text in the buttons is in two lines. Its supposed to be in a single line. on the Blogs page

<img width="614" alt="Screenshot 2020-10-01 at 2 31 19 PM" src="https://user-images.githubusercontent.com/71515238/94789707-e4c4be00-03f2-11eb-8c7f-016221d7e5ea.png">

@mohitgusain @kuldeep3

**Comment by SunnaMalhotra** [comment]
- [ ] Back to blogs button isn't aligned with the heading

<img width="386" alt="Screenshot 2020-10-01 at 2 35 08 PM" src="https://user-images.githubusercontent.com/71515238/94790079-6e748b80-03f3-11eb-9afa-c180560faa76.png">

@mohitgusain @kuldeep3
