### ISSUE TITLE
Homepage : Demo section

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#8]
Design
![image](https://user-images.githubusercontent.com/30264862/93671288-50d42780-fabf-11ea-87d9-21da014f483c.png)

**Comment by bohraji** [comment]
@mohitgusain the play button is not as per the design.

<img width="1085" alt="Screenshot 2020-09-22 at 12 46 49 PM" src="https://user-images.githubusercontent.com/12884297/93853586-bac41b00-fcd1-11ea-9c72-e49a7863f616.png">

**Comment by mohitgusain** [comment]
@bohraji , Not found the exact solution to change the youtube play button styling. If possible can we target it later.

**Comment by bohraji** [comment]
Alright. Closing this for now.
