### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by abhi1203** [coloredcow-admin/glific-website#83]
- [x] Can we please order the section as per the content order on homepage
![image](https://user-images.githubusercontent.com/16714604/94712432-1b54f700-0367-11eb-8dd3-dea1741833af.png)

- [x] Can we remove arrows when there's only one testimonial
![image](https://user-images.githubusercontent.com/16714604/94712532-3d4e7980-0367-11eb-9f56-9f536fdab350.png)

- [x] Small m in Know More
![image](https://user-images.githubusercontent.com/16714604/94712693-74248f80-0367-11eb-9864-20c92701ebf1.png)

- [x] @SunnaMalhotra Can you please make sure only the correct/relevant content shows on the test site now. such as on demo videos page, blog, webinar etc...

- [x] the fonts in this section is not correct
![image](https://user-images.githubusercontent.com/16714604/94713074-f614b880-0367-11eb-9f78-fcd9c552775f.png)

- [x] Let's remove the separator lines in the dropdown.
![image](https://user-images.githubusercontent.com/16714604/94713179-1775a480-0368-11eb-95c5-4c54b954070a.png)

- [x] Is it possible to play the side videos in one click? right now, it first moves to the center then needs another click again. users would be slightly confused what happened
![image](https://user-images.githubusercontent.com/16714604/94713535-8bb04800-0368-11eb-85fb-05a0ea6f0bb8.png)
@abhi1203 , I tried to but I did not get the solution for it. To play the video. It looks  like youtube does not allowing to override the feature

- [x] Let's use the glific green color here. in all the links in faq
![image](https://user-images.githubusercontent.com/16714604/94713643-b8645f80-0368-11eb-9f02-969ec9a5f46f.png)

- [x] increase space between the hamburger menu and book a demo button in smaller devices
![image](https://user-images.githubusercontent.com/16714604/94713790-e47fe080-0368-11eb-8e6a-834b808d6a75.png)

- [x] Can we make the images and text clickable also here
![image](https://user-images.githubusercontent.com/16714604/94714535-e5654200-0369-11eb-8bad-029e0f51a808.png)
Please do the same for recommended reading section also

- [ ] Clicking on reply doesn't do anything. should it open a input box to enter the comment or something
![image](https://user-images.githubusercontent.com/16714604/94718854-f2852f80-036f-11eb-994c-71ed19a1ca1b.png)
@abhi1203 It will redirect again the Post comment form, where you can add more comment

- [x] Clicking on names and tags should filter the blogs by that respective selection

- [x] can we open source code github link in a new tab
![image](https://user-images.githubusercontent.com/16714604/94721360-670d9d80-0373-11eb-889b-339ab6fa07ee.png)

- [ ] Tides svg isn't looking right on safari
![image](https://user-images.githubusercontent.com/16714604/94721601-c1a6f980-0373-11eb-8206-28faa8110882.png)

- [x] The form layout in safari and chrome look different (chrome one is preferred)
![image](https://user-images.githubusercontent.com/16714604/94721639-d1264280-0373-11eb-89e6-2d6e0077035d.png)

- [x] can we have the know more link after the text like the first point 
![image](https://user-images.githubusercontent.com/16714604/94721922-2c583500-0374-11eb-95c8-9f918194239d.png)

- [x] Let's use this link for facebook business verfication https://www.facebook.com/business/help/2058515294227817?id=180505742745347
and this one for gupshup account creation: https://www.gupshup.io/developer/home

- [x] Does it day page not found because the complete link is not present?
![image](https://user-images.githubusercontent.com/16714604/94723023-c371bc80-0375-11eb-9a4c-146ae3ef8ae9.png)

- [x] If you play a video, then click on a video in the side bar and play it. then both the videos start playing. there's no way to stop the previous one. this is happening on features page and not webinar one
![image](https://user-images.githubusercontent.com/16714604/94723129-e4d2a880-0375-11eb-8f58-bffdc4146c8d.png)

- [ ]

**Comment by mohitgusain** [comment]
@abhi1203 , This is ready for testing. Please have a look

**Comment by SunnaMalhotra** [comment]
@mohitgusain I have checked all the boxes of the Issues that have been implemented, The ones that are left or overlapping with my issues have their check boxes empty.

**Comment by SunnaMalhotra** [comment]
### Pending Issue

- [ ] For the replies comment it should say 'zyx replied to xyz'

<img width="1551" alt="Screenshot 2020-10-03 at 8 24 30 PM" src="https://user-images.githubusercontent.com/71515238/94994648-93652c00-05b6-11eb-9ba2-a1152c48cfb1.png">

**Comment by SunnaMalhotra** [comment]
### Pending Issue

- [ ] Tides svg isn't looking right on safari
![94721601-c1a6f980-0373-11eb-8206-28faa8110882](https://user-images.githubusercontent.com/71515238/94994744-52b9e280-05b7-11eb-9693-b9d9ed1a1ce1.png)
