### ISSUE TITLE
Platform testing leftover fixes ( sunna )

### ISSUE THREAD

**Issue by SunnaMalhotra** [coloredcow-admin/glific-website#85]
A few minor fixes left to do

**Comment by SunnaMalhotra** [comment]
Is there a better way to migrate the blog other than copy & pasting them from Chintu Gudiya to the Wordpress dashboard? @mohitgusain @kuldeep3

**Comment by SunnaMalhotra** [comment]
I am not able to edit the Author in the dashboard. so how do I do that? cause on the website to shows up like this.


<img width="183" alt="Screenshot 2020-10-01 at 2 10 10 PM" src="https://user-images.githubusercontent.com/71515238/94790714-4cc7d400-03f4-11eb-9ce1-b698b3031d90.png">

**Comment by SunnaMalhotra** [comment]
The in-text images are being stretched out on the website

<img width="652" alt="Screenshot 2020-10-01 at 2 39 52 PM" src="https://user-images.githubusercontent.com/71515238/94790579-168a5480-03f4-11eb-8b66-dd39ee5b3505.png">

**Comment by SunnaMalhotra** [comment]
Images in this blog are stretched and I am not able to fix it.


<img width="1440" alt="Screenshot 2020-10-02 at 4 27 02 PM" src="https://user-images.githubusercontent.com/71515238/94916391-3bea9180-04cc-11eb-8900-3e68fb96f3cd.png">
 the Images are set to size in the dashboard but they appear like this in this blog
<img width="1440" alt="Screenshot 2020-10-02 at 4 28 01 PM" src="https://user-images.githubusercontent.com/71515238/94916474-5e7caa80-04cc-11eb-879a-28a331745145.png">

**Comment by SunnaMalhotra** [comment]
- [x] **Add, the Glific Demo video 1 in this blog.**
Link- https://www.youtube.com/watch?v=6tQSLj2PIEQ
<img width="1438" alt="Screenshot 2020-10-02 at 5 50 31 PM" src="https://user-images.githubusercontent.com/71515238/94922462-e4eab980-04d7-11eb-9300-d6588732b449.png">

here is where the video will be added.
<img width="793" alt="Screenshot 2020-10-02 at 5 51 23 PM" src="https://user-images.githubusercontent.com/71515238/94922523-02b81e80-04d8-11eb-94f9-772df971ac38.png">

**Comment by SunnaMalhotra** [comment]
- [x] **None of the blogs after the first show more button are clickable** 
When you hover over them it doesn't allow you to click anything there, so those blogs aren't accessible.
<img width="1439" alt="Screenshot 2020-10-02 at 8 27 49 PM" src="https://user-images.githubusercontent.com/71515238/94937934-ddcea600-04ed-11eb-9997-8ad568b22002.png">

**Comment by SunnaMalhotra** [comment]
- [x] This is what it shows as the author of every blog and not their respective authors. on the Wordpress dashboard, there is an option to select authors but not add new authors.

<img width="269" alt="Screenshot 2020-10-02 at 8 30 07 PM" src="https://user-images.githubusercontent.com/71515238/94938235-30a85d80-04ee-11eb-98f6-7fb8e480df1d.png">

**Comment by SunnaMalhotra** [comment]
- [x] The back to blogs button is not aligned with the heading.

<img width="358" alt="Screenshot 2020-10-02 at 10 02 11 PM" src="https://user-images.githubusercontent.com/71515238/94947302-0d37df80-04fb-11eb-9440-49361b8103a6.png">

**Comment by SunnaMalhotra** [comment]
- [x] **The area where you enter your email** and the send button to be **centre aligned to the entire block.**

<img width="1223" alt="Screenshot 2020-10-02 at 10 05 20 PM" src="https://user-images.githubusercontent.com/71515238/94947582-7d466580-04fb-11eb-91b2-d5f0d9869d3f.png">

**Comment by SunnaMalhotra** [comment]
- [x] **Add a link to Tides on the About us page.**

Text -
**Tides is** the SaaS platform run by ColoredCow, they have not yet determined rates. Our initial guess is that for low volumes, it will be in the range of INR 7,500. For higher volumes, it will be a percentage of the messaging costs.

<img width="963" alt="Screenshot 2020-10-02 at 10 09 51 PM" src="https://user-images.githubusercontent.com/71515238/94947949-1ecdb700-04fc-11eb-834f-eab9b4620cc9.png">

**Comment by SunnaMalhotra** [comment]
- [x] **Hide** the **'What are users saying' section** **for now** as we do not have testimonials right now.

<img width="963" alt="Screenshot 2020-10-02 at 10 11 43 PM" src="https://user-images.githubusercontent.com/71515238/94948099-60f6f880-04fc-11eb-9930-c8690ad1c8b8.png">

**Comment by SunnaMalhotra** [comment]
- [x] **Fix this illustration** on the **Why Glific section** on the homepage

<img width="322" alt="Screenshot 2020-10-02 at 10 15 31 PM" src="https://user-images.githubusercontent.com/71515238/94948412-ea0e2f80-04fc-11eb-98b2-c16df9297da5.png">

**Comment by SunnaMalhotra** [comment]
- [x] This is all that shows up for the webinar page.


<img width="1440" alt="Screenshot 2020-10-02 at 10 17 14 PM" src="https://user-images.githubusercontent.com/71515238/94948568-26419000-04fd-11eb-840a-ea2304e53fdc.png">

**Comment by SunnaMalhotra** [comment]
- [x] Update the Tides SVG to a bolder one on the homepage.

File- https://drive.google.com/file/d/13EtTV6L3OQwIYLSVLTbE_leHs7rDgZOd/view?usp=sharing

<img width="322" alt="Screenshot 2020-10-02 at 10 19 34 PM" src="https://user-images.githubusercontent.com/71515238/94948754-79b3de00-04fd-11eb-9280-3ae4002cca85.png">

**Comment by mohitgusain** [comment]
> * [ ]  This is what it shows as the author of every blog and not their respective authors. on the Wordpress dashboard, there is an option to select authors but not add new authors.
> 
> <img alt="Screenshot 2020-10-02 at 8 30 07 PM" width="269" src="https://user-images.githubusercontent.com/71515238/94938235-30a85d80-04ee-11eb-98f6-7fb8e480df1d.png">

@SunnaMalhotra , I think we need to update the blogs again on the new site. Let me have a look once here , and will let you , what we can do here

**Comment by mohitgusain** [comment]
> > * [x]   This is what it shows as the author of every blog and not their respective authors. on the Wordpress dashboard, there is an option to select authors but not add new authors.
> > 
> > <img alt="Screenshot 2020-10-02 at 8 30 07 PM" width="269" src="https://user-images.githubusercontent.com/71515238/94938235-30a85d80-04ee-11eb-98f6-7fb8e480df1d.png">
> 
> @SunnaMalhotra , I think we need to update the blogs again on the new site. Let me have a look once here , and will let you , what we can do here

@SunnaMalhotra I have updated the user to the blogs, can you  check the blog content again
