### ISSUE TITLE
Platform testing : phone ( sunna )

### ISSUE THREAD

**Issue by SunnaMalhotra** [coloredcow-admin/glific-website#87]
#85

**Comment by SunnaMalhotra** [comment]
- [x] The TopBar alignment isn't correct on phone.**

- [x] The hamburger menu is too close too the book a demo button

![IMG_3961](https://user-images.githubusercontent.com/71515238/94949302-52a9dc00-04fe-11eb-90e1-3f63520ea41f.jpg)
This is how it looks on the Sketch file - https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/a/qq0jyV
**<img width="561" alt="Screenshot 2020-10-02 at 10 44 22 PM" src="https://user-images.githubusercontent.com/71515238/94950883-f4322d00-0500-11eb-8f33-2ea5c5a321fe.png">

**Comment by SunnaMalhotra** [comment]
- [x] Book a demo screen opens up on the left side of the screen.

- [x] There is no way to get out of this screen, so we could add a **Not now** text in grey on the right side of the book button

<img width="360" alt="Screenshot 2020-10-02 at 10 27 14 PM" src="https://user-images.githubusercontent.com/71515238/94949444-8c7ae280-04fe-11eb-8033-e0f499d04aec.png">

- [x] after I do manage to exit the book a demo pop-up screen the Book a demo button still looks like its been clicked, It doesn't come back to it original colour.
<img width="360" alt="Screenshot 2020-10-02 at 10 29 11 PM" src="https://user-images.githubusercontent.com/71515238/94949598-d19f1480-04fe-11eb-9452-4635a4d42f10.png">

**Comment by SunnaMalhotra** [comment]
- [ ] The talk to us button isn't clickable

<img width="360" alt="Screenshot 2020-10-02 at 10 29 56 PM" src="https://user-images.githubusercontent.com/71515238/94949666-ec718900-04fe-11eb-886e-1aac100565b1.png">

**Comment by SunnaMalhotra** [comment]
- [ ] The resources text in the hamburger menu isn't expandable ( blogs, Webinar, FAQs ) or clickable.

<img width="360" alt="Screenshot 2020-10-02 at 10 30 44 PM" src="https://user-images.githubusercontent.com/71515238/94949734-090dc100-04ff-11eb-8120-d7370916ebec.png">
 Okay, so I managed to click it but I am guessing only the small arrow is clickable, can we make the entire text clickable.

**Comment by SunnaMalhotra** [comment]
- [ ] The sign up for newsletter block has too much space at the bottom of the sign up button. the spacing should be equal on the top and bottom.

<img width="360" alt="Screenshot 2020-10-02 at 10 33 56 PM" src="https://user-images.githubusercontent.com/71515238/94950000-7c173780-04ff-11eb-99bf-1e216aa398fe.png">

**Comment by SunnaMalhotra** [comment]
- [x] The screen looks fine on 360px, but on 320px a horizontal scroll gets added. So can we make it as equally equipped for 320px as it is for 360px. Basically, making it adjustable to different phone screen sizes as well, specially the smaller sizes.

- Every thing gets a little cut from the sides

- [ ] If possible can we have a 10px spacing from the left and right sides of the screen.

<img width="358" alt="Screenshot 2020-10-02 at 10 37 43 PM" src="https://user-images.githubusercontent.com/71515238/94950279-0364ab00-0500-11eb-81ca-56d3cdbf13e4.png">

**Comment by SunnaMalhotra** [comment]
- [x] In 320px, there is a lot of white space on the right side of the screen but no white space on the left side . Probably because of horizontal scroll. we need to remove that.

<img width="340" alt="Screenshot 2020-10-02 at 10 40 56 PM" src="https://user-images.githubusercontent.com/71515238/94950572-766e2180-0500-11eb-965f-1f55f3c31257.png">

- [x] Book a demo opens up wonky here as well.

<img width="359" alt="Screenshot 2020-10-02 at 10 42 10 PM" src="https://user-images.githubusercontent.com/71515238/94950681-a3223900-0500-11eb-848b-0cba6d822b65.png">

**Comment by mohitgusain** [comment]
> * [ ]  Book a demo screen opens up on the left side of the screen.
> * [ ]  There is no way to get out of this screen, so we could add a **Not now** text in grey on the right side of the book button

@SunnaMalhotra I have added the crossbar at the top of the modal to get out from it.
> 
> <img alt="Screenshot 2020-10-02 at 10 27 14 PM" width="360" src="https://user-images.githubusercontent.com/71515238/94949444-8c7ae280-04fe-11eb-8033-e0f499d04aec.png">
> 
> * [ ]  after I do manage to exit the book a demo pop-up screen the Book a demo button still looks like its been clicked, It doesn't come back to it original colour.
@SunnaMalhotra , it's a browser bahviour,once you will also click back to the screen. it goes away/
> 
> <img alt="Screenshot 2020-10-02 at 10 29 11 PM" width="360" src="https://user-images.githubusercontent.com/71515238/94949598-d19f1480-04fe-11eb-9452-4635a4d42f10.png">

**Comment by mohitgusain** [comment]
> * [ ]  The sign up for newsletter block has too much space at the bottom of the sign up button. the spacing should be equal on the top and bottom.
> 
> <img alt="Screenshot 2020-10-02 at 10 33 56 PM" width="360" src="https://user-images.githubusercontent.com/71515238/94950000-7c173780-04ff-11eb-99bf-1e216aa398fe.png">
@SunnaMalhotra , this space is coming to the captcha , which is hidden in the form. We can remove it for now.
