### ISSUE TITLE
Blog page feedback

### ISSUE THREAD

**Issue by abhi1203** [coloredcow-admin/glific-website#88]
Date is appearing in the blog url. can we remove that?
![image](https://user-images.githubusercontent.com/16714604/95172811-7ce8eb80-07d5-11eb-9629-fd2841b92197.png)

**Comment by abhi1203** [comment]
The blog links should be glific bright green color #119656
![image](https://user-images.githubusercontent.com/16714604/95173006-bc173c80-07d5-11eb-8fd5-4f3ee7726958.png)

**Comment by abhi1203** [comment]
can we remove this share buttons since it's already there on the right
![image](https://user-images.githubusercontent.com/16714604/95173216-01d40500-07d6-11eb-8ea4-3791635538dd.png)

these share buttons should scroll with the page till the comment section
![image](https://user-images.githubusercontent.com/16714604/95173268-12847b00-07d6-11eb-9e6e-52f79426f0c7.png)

**Comment by mohitgusain** [comment]
> can we remove this share buttons since it's already there on the right
> ![image](https://user-images.githubusercontent.com/16714604/95173216-01d40500-07d6-11eb-8ea4-3791635538dd.png)
> 
> these share buttons should scroll with the page till the comment section
> ![image](https://user-images.githubusercontent.com/16714604/95173268-12847b00-07d6-11eb-9e6e-52f79426f0c7.png)
@abhi1203 , This is a bit complex to scroll it till the comment section. Secondly, these buttons also in the mobile are align in a different way and it will look like a broken. Can we keep it for now.

**Comment by mohitgusain** [comment]
> The blog links should be glific bright green color #119656
> ![image](https://user-images.githubusercontent.com/16714604/95173006-bc173c80-07d5-11eb-8fd5-4f3ee7726958.png)

@abhi1203, This fixed in the UAT site. You can test it there
