### ISSUE TITLE
Google Analytics Addition

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#90]
1. Need to add Google analytics for the Plugin

**Comment by mohitgusain** [comment]
@bohraji  Google analytics has been placed within the site Dashboard. We can check it by on clicking on the `Insights` menu from the dashboard. Here is the screenshot of the analytic so far.
![image](https://user-images.githubusercontent.com/30264862/95291373-fee81b80-088c-11eb-84cd-cf63e4f6340a.png)

**Comment by bohraji** [comment]
@mohitgusain please add the link to access the analytics and the account from which it can be accessed in the same document that is being added on #43

**Comment by bohraji** [comment]
Closing this since it can be done from the same Wordpress dashboard.
