### ISSUE TITLE
Need to add new features to the features page

### ISSUE THREAD

**Issue by abhi1203** [coloredcow-admin/glific-website#99]
- [x] Simulator

- [x] Analytics and reporting with chatbase/bigquery

- [ ] google sheet integration

**Comment by SunnaMalhotra** [comment]
This is the GIF for the Simulator.
Link- https://drive.google.com/file/d/1cb2ULpQp5YbXq2cPcCJKjVpWzuVxuDhK/view?usp=sharing

**Comment by SunnaMalhotra** [comment]
This is the GIF for the Analytics feature.
Link- https://drive.google.com/file/d/1N4DLWHPGN8ZK_yzr9q_GMBnF-BgMRWMe/view?usp=sharing

**Comment by SunnaMalhotra** [comment]
The design for the features.
Dekstop- https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/v/xK04Yx/a/4z5pmx/r/Lb43LQ
Tablet- https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/v/xK04Yx/a/JwKbqM/r/Lb43LQ
Phone- https://www.sketch.com/s/a59f24ce-42ce-4488-bc8d-b52b7e47c00c/v/xK04Yx/a/vPMqb1/r/Lb43LQ

**Comment by SunnaMalhotra** [comment]
The GIF for google sheet integration to make automated flows.https://drive.google.com/file/d/1NvGrhIJHpZk7VvJM1HXhqm5DprGcl01e/view?usp=sharing

**Comment by abhi1203** [comment]
This is done.. closing.
